daemon:
  watch_poll_interval: 5
mcp:
  servers:
    slack:
      enabled: true
      approval_policy: allow
      command: npx
      args:
      - "-y"
      - "slack-mcp-server@latest"
      - "--transport"
      - "stdio"
    # chrome-devtools:
    #   command: npx
    #   args:
    #     - "-y"
    #     - chrome-devtools-mcp@latest
    #     - "-u"
    #     - http://localhost:9222
    #   enabled: true
    #   approval_policy: allow
    #   env: {}
    #   cwd: null
    # mock-server:
    #   command: node
    #   args:
    #     - tmp/mock-mcp-server.mjs
    #   enabled: true
    #   approval_policy: allow
    #   env: {}
    #   cwd: null
github:
  device_code_url: https://github.com/login/device/code
  access_token_url: https://github.com/login/oauth/access_token
  client_id: Iv1.b507a08c87ecfe98
  user_agent: GitHubCopilotChat/0.26.7
copilot:
  access_token_max_poll_timeout: 300000
  api_key_url: https://api.github.com/copilot_internal/v2/token
  default_api_url: https://api.githubcopilot.com
  user_agent: GitHubCopilotChat/0.26.7
  editor_version: vscode/1.99.3
  editor_plugin_version: copilot-chat/0.26.7
  integration_id: vscode-chat
